name: CI

on:
  push:
    branches:
      - master
    tags-ignore:
      - 'release-*'
    paths:
      - 'luci-app-wrtbwmon/**'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build the IPK
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Docker Build
      run: |
        mkdir bin
        cp -rf ./luci-app-wrtbwmon ./bin/
        docker pull openwrtorg/sdk:x86-64-19.07-SNAPSHOT
        docker run --rm -u root -v "$(pwd)"/bin/:/home/build/openwrt/bin -v ${{ github.workspace }}/.github/workflows:/home/build/workflows openwrtorg/sdk:x86-64-19.07-SNAPSHOT /bin/sh /home/build/workflows/build.sh
    - name: Upload app
      uses: actions/upload-artifact@v2
      with:
        name: luci-app-wrtbwmon
        path: ./bin/packages/x86_64/base/*wrtbwmon*
        if-no-files-found: error
    - name: Upload Log
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: buildlog
        path: bin/logs.tar.xz
